# Configuration file for the Sphinx documentation builder.
# PhoenixDRS - Professional Data Recovery Suite Documentation

import os
import sys

# -- Path setup --------------------------------------------------------------
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------
project = 'PhoenixDRS'
copyright = '2024, PhoenixDRS Development Team'
author = 'PhoenixDRS Development Team'
release = '1.0.0'
version = '1.0.0'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',  # For Google/NumPy style docstrings
    'myst_parser',  # For Markdown support
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': None,
    '.md': None,
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

html_static_path = ['_static']
html_css_files = ['custom.css']
html_js_files = ['custom.js']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# -- Options for HTMLHelp output ---------------------------------------------
htmlhelp_basename = 'PhoenixDRSdoc'

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'preamble': '',
    'figure_align': 'htbp',
}

latex_documents = [
    (master_doc, 'PhoenixDRS.tex', 'PhoenixDRS Documentation',
     'PhoenixDRS Development Team', 'manual'),
]

# -- Options for manual page output ------------------------------------------
man_pages = [
    (master_doc, 'phoenixdrs', 'PhoenixDRS Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------
texinfo_documents = [
    (master_doc, 'PhoenixDRS', 'PhoenixDRS Documentation',
     author, 'PhoenixDRS', 'Professional Data Recovery Suite.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------
epub_title = project
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------
intersphinx_mapping = {
    'https://docs.python.org/3/': None,
    'https://docs.pytest.org/en/stable/': None,
}

# -- Options for todo extension ----------------------------------------------
todo_include_todos = True

# -- Options for autodoc extension -------------------------------------------
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Automatically extract typehints
autodoc_typehints = 'description'
autodoc_typehints_description_target = 'documented'

# -- Options for autosummary extension ---------------------------------------
autosummary_generate = True

# -- Options for Napoleon extension ------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for MyST Parser extension --------------------------------------
myst_enable_extensions = [
    "deflist",
    "tasklist",
    "html_admonition",
    "html_image",
    "colon_fence",
    "smartquotes",
    "replacements",
    "linkify",
    "strikethrough",
]

myst_heading_anchors = 3

# -- Custom configuration for PhoenixDRS ------------------------------------

# Add custom CSS and JS
def setup(app):
    app.add_css_file('custom.css')
    app.add_js_file('custom.js')

# Version info for the project
rst_epilog = """
.. |version| replace:: {version}
.. |release| replace:: {release}
.. |today| replace:: {today}
""".format(
    version=version,
    release=release,
    today=os.popen('date').read().strip()
)

# Custom roles for documentation
rst_prolog = """
.. role:: python(code)
   :language: python
   :class: highlight

.. role:: bash(code)
   :language: bash
   :class: highlight

.. role:: json(code)
   :language: json
   :class: highlight
"""

# Suppress specific warnings
suppress_warnings = [
    'image.nonlocal_uri',
    'ref.ref',
]

# Enable figure numbering
numfig = True
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': 'Section %s',
}

# Internationalization
locale_dirs = ['locale/']
gettext_compact = False

# Additional options for better documentation
add_function_parentheses = True
add_module_names = True
show_authors = True

# GitHub integration
html_context = {
    "display_github": True,
    "github_user": "phoenixdrs",
    "github_repo": "phoenixdrs",
    "github_version": "main",
    "conf_py_path": "/docs/",
}

# Search options
html_search_options = {'type': 'default'}

# Enable copy button for code blocks
html_theme_options.update({
    "use_edit_page_button": True,
})

# Custom footer
html_last_updated_fmt = '%b %d, %Y'
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True